
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the latest LTS version of Node.js

    - name: Install dependencies
      run: npm install

    - name: Run Hello World
      run: npm start

    - name: Run tests
      run: npm test
