name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the latest LTS version of Node.js

    - name: Install dependencies
      run: npm install

    - name: Run Build Script
      run: npm build  # Assuming you have a build script in package.json

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the test job runs only after the build job completes successfully

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm test  # This runs your Jest tests
