name: Data passing workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate data
        run: echo "some data generated in job1" > data.txt

      - name: Upload data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-artifact
          path: data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download data artifact
        uses: actions/download-artifact@v3
        with:
          name: data-artifact

      - name: Display data
        run: cat data.txt
