name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Updated to latest version

      - name: Generate data
        run: echo "some data generated in job1" > data.txt

      - name: Upload data as artifact
        uses: actions/upload-artifact@v4   # Updated to latest version
        with:
          name: data-artifact
          path: data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Updated to latest version

      - name: Download data artifact
        uses: actions/download-artifact@v4   # Updated to latest version
        with:
          name: data-artifact

      - name: Create GitHub Release
        run: |
          gh release create v1.0.0 ./data.txt --title "Release v1.0.0" --notes "This is the first release."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: echo "Asset uploaded"  # The `gh release create` command already handles uploading assets
